### ISSUE TITLE
有一个不推送到aira2的bug呐

### ISSUE THREAD

**Issue by 757321061** [CJReinforce/PikPakAutoOfflineDownloadBot#23]
/p magnet:?xt=urn:btih:9b95d274a3fbdaf00c73c6dff5bea16fca824fa2 magnet:?xt=urn:btih:efddf2cd23b2fc5b7f2fb591b84b37623a151d69 magnet:?xt=urn:btih:df372659b2afdb9b497249a671d1b65e60cdc924 magnet:?xt=urn:btih:5bc890c37493fe48a087cc519b7dc912e323a717 magnet:?xt=urn:btih:18d697e35d0f756ac0c0476337bf2200224850b7 magnet:?xt=urn:btih:8b91f3160d38c042a2c4f1e91ea5d0f7cf879261 magnet:?xt=urn:btih:392ebd6d85aca9ce0794bd46b0f2a87beb5603ca magnet:?xt=urn:btih:1601ddc62f5e601f89c245133d8ccbd2cc5d03b5 magnet:?xt=urn:btih:cbf43efb2e1c6f34c64013d906a4e9f6a194ea51 magnet:?xt=urn:btih:f8491d5b36ba54dc02e102a7dc72fca49522b8e8 magnet:?xt=urn:btih:588b7c7cf940248bb2ce36ceed3c9b706d5c5674 magnet:?xt=urn:btih:b2510ee4e014a27cf4a1c10c39c3a5d04446cd40 magnet:?xt=urn:btih:7e7adac7e8034dc8100ff34dbeb80e3046ed5da9 magnet:?xt=urn:btih:dae59cb178dd3b72e698fcfca5b53ca6df085ea5 magnet:?xt=urn:btih:0e372a8d08cf46dc30f4ad5fe8edc3a92bf21380 magnet:?xt=urn:btih:58b870bd81c314cc6f7b4476fb600d0ebeb97875

这是我的磁力
发送后
![image](https://github.com/CJReinforce/PikPakAutoOfflineDownloadBot/assets/49135603/90de1af0-f73b-4159-bc94-8680467b12c9)
然后 他全下载到网盘了  

然后推送aira2 只推送了 10个
![image](https://github.com/CJReinforce/PikPakAutoOfflineDownloadBot/assets/49135603/f194216b-b7a4-4be3-9c99-69cf51b3cbcf)

日志也只有十个
文件名称：[NC-Raws] 炼气练了3000年 - 01 (B-Global Donghua 1920x1080 HEVC AAC MKV) [1BA3BBE9].mkv
2023-09-27 19:52:16,098 - INFO - 磁链magnet:?xt=urn:btih:f8491d5b36ba54dc02e102a7dc72fca49522b8e8内容为单文件，将直接推送aria2下载
2023-09-27 19:52:16,284 - INFO - 磁链magnet:?xt=urn:btih:7e7adac7e8034dc8100ff34dbeb80e3046ed5da9内容为单文件，将直接推送aria2下载
2023-09-27 19:52:16,302 - INFO - 磁链magnet:?xt=urn:btih:18d697e35d0f756ac0c0476337bf2200224850b7内容为单文件，将直接推送aria2下载
2023-09-27 19:52:16,873 - INFO - 磁链magnet:?xt=urn:btih:58b870bd81c314cc6f7b4476fb600d0ebeb97875内容为单文件，将直接推送aria2下载
2023-09-27 19:52:19,968 - INFO - 账号jinshenganyuci@gmail.com离线下载磁链已完成：

  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 230, in _parse
    self._target(*self._args, **self._kwargs)
  File "/root/PikPakAutoOfflineDownloadBot/pikpakTgBot.py", line 533, in main
    context.bot.send_message(chat_id=update.effective_chat.id, text=f'文件已推送aria2下载：\n{down_name}\n请耐心等待...')
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 133, in decorator

    message = str(self._parse(resp.data))
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 230, in _parse
    raise RetryAfter(retry_after)
telegram.error.RetryAfter: Flood control exceeded. Retry in 5.0 seconds
2023-09-27 19:52:20,577 - INFO - 磁链magnet:?xt=urn:btih:b2510ee4e014a27cf4a1c10c39c3a5d04446cd40内容为单文件，将直接推送aria2下载
2023-09-27 19:52:20,608 - INFO - 磁链magnet:?xt=urn:btih:efddf2cd23b2fc5b7f2fb591b84b37623a151d69内容为单文件，将直接推送aria2下载
2023-09-27 19:52:20,652 - INFO - 磁链magnet:?xt=urn:btih:1601ddc62f5e601f89c245133d8ccbd2cc5d03b5内容为单文件，将直接推送aria2下载
2023-09-27 19:52:20,657 - INFO - 磁链magnet:?xt=urn:btih:8b91f3160d38c042a2c4f1e91ea5d0f7cf879261内容为单文件，将直接推送aria2下载
2023-09-27 19:52:21,004 - INFO - 磁链magnet:?xt=urn:btih:cbf43efb2e1c6f34c64013d906a4e9f6a194ea51内容为单文件，将直接推送aria2下载

**Comment by 757321061** [comment]
好像找到原因了  可能是 telegram api 请求速度过快 这个要怎么改

**Comment by 757321061** [comment]
文件名称：[NC-Raws] 炼气练了3000年 - 08 (B-Global Donghua 1920x1080 HEVC AAC MKV) [81DCCA0E].mkv
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PikPakAutoOfflineDownloadBot/pikpakTgBot.py", line 533, in main
    context.bot.send_message(chat_id=update.effective_chat.id, text=f'文件已推送aria2下载：\n{down_name}\n请耐心等待...')
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 525, in send_message
    return self._message(  # type: ignore[return-value]
  File "/usr/local/lib/python3.9/dist-packages/telegram/ext/extbot.py", line 202, in _message
    result = super()._message(
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 339, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 272, in _request_wrapper
    message = str(self._parse(resp.data))
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 230, in _parse
    raise RetryAfter(retry_after)
telegram.error.RetryAfter: Flood control exceeded. Retry in 5.0 seconds
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PikPakAutoOfflineDownloadBot/pikpakTgBot.py", line 431, in main
    context.bot.send_message(chat_id=update.effective_chat.id, text=print_info)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 525, in send_message
    return self._message(  # type: ignore[return-value]
  File "/usr/local/lib/python3.9/dist-packages/telegram/ext/extbot.py", line 202, in _message
    result = super()._message(
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 339, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 272, in _request_wrapper
    message = str(self._parse(resp.data))
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 230, in _parse
    raise RetryAfter(retry_after)
telegram.error.RetryAfter: Flood control exceeded. Retry in 5.0 seconds
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PikPakAutoOfflineDownloadBot/pikpakTgBot.py", line 431, in main
    context.bot.send_message(chat_id=update.effective_chat.id, text=print_info)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 525, in send_message
    return self._message(  # type: ignore[return-value]
  File "/usr/local/lib/python3.9/dist-packages/telegram/ext/extbot.py", line 202, in _message
    result = super()._message(
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 339, in _message
2023-09-27 19:52:20,211 - WARNING - Connection pool is full, discarding connection: api.telegram.org
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 298, in _post
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    return self.request.post(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 361, in post
    self.run()
2023-09-27 19:52:20,213 - WARNING - Connection pool is full, discarding connection: api.telegram.org
    result = self._request_wrapper(
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 892, in run
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 272, in _request_wrapper
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    message = str(self._parse(resp.data))
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 230, in _parse
    self._target(*self._args, **self._kwargs)
  File "/root/PikPakAutoOfflineDownloadBot/pikpakTgBot.py", line 533, in main
    context.bot.send_message(chat_id=update.effective_chat.id, text=f'文件已推送aria2下载：\n{down_name}\n请耐心等待...')
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 133, in decorator
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PikPakAutoOfflineDownloadBot/pikpakTgBot.py", line 431, in main
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 525, in send_message
    raise RetryAfter(retry_after)
    context.bot.send_message(chat_id=update.effective_chat.id, text=print_info)
    return self._message(  # type: ignore[return-value]
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/ext/extbot.py", line 202, in _message
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 525, in send_message
    result = super()._message(
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 339, in _message
    return self._message(  # type: ignore[return-value]
  File "/usr/local/lib/python3.9/dist-packages/telegram/ext/extbot.py", line 202, in _message
telegram.error.RetryAfter: Flood control exceeded. Retry in 5.0 seconds
    result = super()._message(
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 339, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 298, in _post
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 361, in post
    return self.request.post(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 272, in _request_wrapper
    result = self._request_wrapper(
    message = str(self._parse(resp.data))
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 230, in _parse
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 272, in _request_wrapper
    raise RetryAfter(retry_after)
2023-09-27 19:52:20,220 - WARNING - Connection pool is full, discarding connection: api.telegram.org
telegram.error.RetryAfter: Flood control exceeded. Retry in 5.0 seconds
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PikPakAutoOfflineDownloadBot/pikpakTgBot.py", line 431, in main
    message = str(self._parse(resp.data))
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 230, in _parse
    raise RetryAfter(retry_after)
telegram.error.RetryAfter: Flood control exceeded. Retry in 5.0 seconds
    context.bot.send_message(chat_id=update.effective_chat.id, text=print_info)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 525, in send_message
    return self._message(  # type: ignore[return-value]
  File "/usr/local/lib/python3.9/dist-packages/telegram/ext/extbot.py", line 202, in _message
    result = super()._message(
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 339, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 272, in _request_wrapper
    message = str(self._parse(resp.data))
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 230, in _parse
    raise RetryAfter(retry_after)
telegram.error.RetryAfter: Flood control exceeded. Retry in 5.0 seconds
2023-09-27 19:52:20,227 - WARNING - Connection pool is full, discarding connection: api.telegram.org
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PikPakAutoOfflineDownloadBot/pikpakTgBot.py", line 431, in main
    context.bot.send_message(chat_id=update.effective_chat.id, text=print_info)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 525, in send_message
    return self._message(  # type: ignore[return-value]
  File "/usr/local/lib/python3.9/dist-packages/telegram/ext/extbot.py", line 202, in _message
    result = super()._message(
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 339, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 272, in _request_wrapper
2023-09-27 19:52:20,231 - WARNING - Connection pool is full, discarding connection: api.telegram.org
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    message = str(self._parse(resp.data))
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 230, in _parse
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    raise RetryAfter(retry_after)
telegram.error.RetryAfter: Flood control exceeded. Retry in 5.0 seconds
    self._target(*self._args, **self._kwargs)
  File "/root/PikPakAutoOfflineDownloadBot/pikpakTgBot.py", line 431, in main
    context.bot.send_message(chat_id=update.effective_chat.id, text=print_info)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 525, in send_message
    return self._message(  # type: ignore[return-value]
  File "/usr/local/lib/python3.9/dist-packages/telegram/ext/extbot.py", line 202, in _message
    result = super()._message(
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 339, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 272, in _request_wrapper
    message = str(self._parse(resp.data))
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 230, in _parse
    raise RetryAfter(retry_after)
telegram.error.RetryAfter: Flood control exceeded. Retry in 5.0 seconds
2023-09-27 19:52:20,240 - WARNING - Connection pool is full, discarding connection: api.telegram.org
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PikPakAutoOfflineDownloadBot/pikpakTgBot.py", line 533, in main
    context.bot.send_message(chat_id=update.effective_chat.id, text=f'文件已推送aria2下载：\n{down_name}\n请耐心等待...')
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 525, in send_message
    return self._message(  # type: ignore[return-value]
  File "/usr/local/lib/python3.9/dist-packages/telegram/ext/extbot.py", line 202, in _message
    result = super()._message(
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 339, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 272, in _request_wrapper
    message = str(self._parse(resp.data))
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 230, in _parse
    raise RetryAfter(retry_after)
telegram.error.RetryAfter: Flood control exceeded. Retry in 5.0 seconds
2023-09-27 19:52:20,295 - WARNING - Connection pool is full, discarding connection: api.telegram.org
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PikPakAutoOfflineDownloadBot/pikpakTgBot.py", line 533, in main
    context.bot.send_message(chat_id=update.effective_chat.id, text=f'文件已推送aria2下载：\n{down_name}\n请耐心等待...')
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 525, in send_message
    return self._message(  # type: ignore[return-value]
  File "/usr/local/lib/python3.9/dist-packages/telegram/ext/extbot.py", line 202, in _message
    result = super()._message(
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 339, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 272, in _request_wrapper
    message = str(self._parse(resp.data))
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 230, in _parse
    raise RetryAfter(retry_after)
telegram.error.RetryAfter: Flood control exceeded. Retry in 5.0 seconds
2023-09-27 19:52:20,321 - WARNING - Connection pool is full, discarding connection: api.telegram.org
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/PikPakAutoOfflineDownloadBot/pikpakTgBot.py", line 533, in main
    context.bot.send_message(chat_id=update.effective_chat.id, text=f'文件已推送aria2下载：\n{down_name}\n请耐心等待...')
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 525, in send_message
    return self._message(  # type: ignore[return-value]
  File "/usr/local/lib/python3.9/dist-packages/telegram/ext/extbot.py", line 202, in _message
    result = super()._message(
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 339, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 272, in _request_wrapper
    message = str(self._parse(resp.data))
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils/request.py", line 230, in _parse
    raise RetryAfter(retry_after)
telegram.error.RetryAfter: Flood control exceeded. Retry in 5.0 seconds

**Comment by 757321061** [comment]
忘了说了，我这是在我的群组内发送的， 机器人给群组发送消息太频繁了，怎么样才能限制发言速度
