### ISSUE TITLE
I checked the token is true 

### ISSUE THREAD

**Issue by Daoker01** [CJReinforce/PikPakAutoOfflineDownloadBot#8]
2022-07-05 08:05:03,016 - INFO - Scheduler started
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "pikpakTgBot.py", line 315, in main
    login(each_account)  # 指定用哪个账户登录
  File "pikpakTgBot.py", line 67, in login
    headers['Authorization'] = f"Bearer {info['access_token']}"
KeyError: 'access_token'

**Comment by oldjerry** [comment]
This error is failed of pikpak login，the info of login pikpak without 'access_token'. it's not about TG token。
you'll check the username and PWD with your pikpak account.
